runtime: python312 # Or appropriate Python version
service: api
env: standard
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
handlers:
- url: /.*
  script: auto
  secure: always
vpc_access_connector:
  name: projects/hku-capstone-project-458309/locations/asia-east2/connectors/hku-vpc-connector-subnet
